awprintlabel_form_configuration:
  path: /awprintlabel/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Axelweb\AwPrintLabel\Controller\AdminConfigurationController::index'

awprintlabel_print_label:
    path: /awprintlabel/print-label
    methods: [GET]
    defaults:
      _controller: 'Axelweb\AwPrintLabel\Controller\PrintLabelController::index'
      _legacy_controller: PrintLabel
      _legacy_link: PrintLabel
