awprintlabel_form_configuration:
  path: /awprintlabel/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Axelweb\AwPrintLabel\Controller\AdminConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: AdminAwPrintLabel
    _legacy_link: AdminAwPrintLabel
